name: 'allurectl install'
description: 'Install allurectl tool'
author: 'Qameta Software'
inputs:
  version:
    required: true
    description: 'The allurectl version to make available on the path'
  architecture:
    required: false
    description: 'The architecture (x86, x64) of the package'
    default: "x64"
runs:
  using: 'node12'
  main: 'dist/index.js'
